services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${DB_UI_PORT}:${DB_UI_PORT}"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_UI_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_UI_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "${DB_URL}"
